import = [
	"~/.config/alacritty/catppuccin-mocha.toml",
]

ipc_socket = true

[window]
title = "Alacritty  "
dynamic_title = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.7
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.5
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 2.0
smooth_motion_max_stretch_y = 2.0

style = {shape = "beam", blinking = "off"}

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[mouse]
bindings = [
	{ mouse = "Right", mods = "Control", action = "Paste" },
]
