#!/usr/bin/env bash

# Options
performance='󰓅 Performance'
medium='󰾅 Balance'
power='󰾆 Power Saver'

rofi_cmd() {
	rofi -dmenu
}


# Confirmation CMD
confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 1; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?'
}

confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}


# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$performance\n$medium\n$power" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$yes"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--performance' ]]; then
			powerprofilesctl set performance
			notify-send "Power set to performance mode"
		elif [[ $1 == '--medium' ]]; then
			powerprofilesctl set balanced
			notify-send "Power set to balance mode"
		elif [[ $1 == '--power' ]]; then
			powerprofilesctl set power-saver
			notify-send "Power set to power-saver mode"
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $performance)
		run_cmd --performance
        ;;
    $medium)
		run_cmd --medium
        ;;
    $power)
		run_cmd --power
        ;;
esac

