# Here is global, all global key cant conflicts with other hotkeys
quit = ['esc', '']
# 
list_up = ['up', '']
list_down = ['down', '']
# 
pinned_directory = ['P', '']
# 
close_file_panel = [']', '']
create_new_file_panel = ['[', '']
# 
next_file_panel = ['ctrl+right', 'tab']
previous_file_panel = ['ctrl+left', 'shift+tab']
focus_on_process_bar = ['X', '']
focus_on_side_bar = ['Z', '']
focus_on_metadata = ['C', '']
# 
change_panel_mode = ['', '']
open_help_menu = ['?', '']
# 
file_panel_directory_create = ['D', '']
file_panel_file_create = ['C', '']
file_panel_item_rename = ['r', '']
paste_item = ['ctrl+v', '']
extract_file = ['ctrl+a', '']
compress_file = ['ctrl+e', '']
toggle_dot_file = ['H', '']
# 
oepn_file_with_editor = ['ctrl+o', '']
open_current_directory_with_editor = ['ctrl+o', '']
# 
# These hotkeys do not conflict with any other keys (including global hotkey)
cancel = ['q', '']
confirm = ['enter', '']
# 
# Here is normal mode hotkey you can conflicts with other mode (cant conflicts with global hotkey)
delete_item = ['delete', 'shift+d']
select_item = ['right', 'enter']
parent_directory = ['left', '']
copy_single_item = ['ctrl+c', '']
cut_single_item = ['ctrl+x', '']
search_bar = ['/', '']
command_line = ['\', '']
# 
# Here is select mode hotkey you can conflicts with other mode (cant conflicts with global hotkey)
file_panel_select_mode_item_single_select = ['', '']
file_panel_select_mode_item_select_down = ['', '']
file_panel_select_mode_item_select_up = ['', '']
file_panel_select_mode_item_delete = ['', '']
file_panel_select_mode_item_copy = ['', '']
file_panel_select_mode_item_cut = ['', '']
file_panel_select_all_item = ['', '']
